@echo off
chcp 65001 >nul
CD /d "%~dp0"
Title Reg Converter v1.2 & Color 1A
cd %systemroot%\system32
call :IsAdmin

Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DictHistorySize" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DictMask" /t REG_SZ /d "0000001100000000000000000000000000000000000000000000000000000000000000000" /f
Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DictLimit" /t REG_DWORD /d "10" /f
Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DefFolder" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Vol5MB" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Vol100MB" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "CD700" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Vol2GB" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "FAT32" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "DVD+R" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "DVD-R" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "DVD DL" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Blu-ray" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Blu-ray DL" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Autodetect" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "History" /t REG_DWORD /d "3" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel0" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize0" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel1" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize1" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel2" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize2" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel3" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize3" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\DialogEditHistory\ArcName" /v "0" /t REG_SZ /d "D:\Temp\Apps Portable\My_PC'D'_PortableApps.exe" /f
Reg.exe add "HKCU\Software\WinRAR\DialogEditHistory\ArcName" /v "1" /t REG_SZ /d "D:\Temp\Apps Portable\My_PC'D'_PortableAppsShortcuts.exe" /f
Reg.exe add "HKCU\Software\WinRAR\DialogEditHistory\ArcName" /v "2" /t REG_SZ /d "D:\Temp\Apps Portable\_DataFolders\_Morph3us\AlecaFrame.rar" /f
Reg.exe add "HKCU\Software\WinRAR\DialogEditHistory\ArcName" /v "3" /t REG_SZ /d "D:\Temp\Apps Portable\_DataFolders\_Morph3us\ChromeUserData.rar" /f
Reg.exe add "HKCU\Software\WinRAR\DialogEditHistory\ArcName" /v "4" /t REG_SZ /d "D:\Temp\Apps Portable\_DataFolders\_Morph3us\ChromiumUserData.rar" /f
Reg.exe add "HKCU\Software\WinRAR\DialogEditHistory\DictSize" /v "0" /t REG_SZ /d "64 MB" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "DefFolder" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "AppendName" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "RemoveRedundantFolder" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "UseExclNames" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "ExclNames" /t REG_SZ /d "*.exe *.com *.pif *.scr *.bat *.cmd *.lnk" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "MOTWMode" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "MOTWZoneOnly" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Detailed" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ArchivesFirst" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ColorAttr" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "AllVolumes" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ShowSeconds" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ExactSizes" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ShowGrid" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "FullRow" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Checkboxes" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "SingleClick" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Underline" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ArcSort" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "FileSort" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Font" /t REG_BINARY /d "efffffff0000000000000000000000009001000000000000030201225300650067006f006500200055004900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "FontColorDark" /t REG_DWORD /d "16777215" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "name" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "size" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "psize" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "type" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "mtime" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "ctime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "atime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "attr" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "crc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "path" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "name" /t REG_DWORD /d "304" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "size" /t REG_DWORD /d "101" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "psize" /t REG_DWORD /d "101" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "type" /t REG_DWORD /d "129" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "mtime" /t REG_DWORD /d "146" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "crc" /t REG_DWORD /d "70" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "name" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "size" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "psize" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "type" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "mtime" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "ctime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "atime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "attr" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "crc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "path" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "name" /t REG_DWORD /d "307" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "size" /t REG_DWORD /d "101" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "type" /t REG_DWORD /d "214" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "mtime" /t REG_DWORD /d "147" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "VerInfo" /t REG_BINARY /d "000d0700c78cf5b37f08dc01" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "History" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "DlgHistory" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "WizardMode" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "OnTop" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "ShowComment" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "WrapComment" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "ReuseWindow" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Sound" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Priority" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Threads" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LargePages" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Log" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LimitLog" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LogSize" /t REG_DWORD /d "1000" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "RestoreFolder" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "WipeTemp" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LastFolder" /t REG_SZ /d "D:\Temp\Apps Portable" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar" /v "Size" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar" /v "ButtonsText" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar" /v "Lock" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Layout" /v "Band76_0" /t REG_BINARY /d "4c000000610100000402000000000000000000000000000000000000000000000000000000000000000000000000000000000000550000004403000000000000000000000000000001000000" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Layout" /v "Band76_1" /t REG_BINARY /d "4c0000006101000005000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b0000002600000000000000000000000000000002000000" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Layout" /v "Band76_2" /t REG_BINARY /d "4c0000006101000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b0000006400000000000000000000000000000003000000" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "ColorMode" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "FullPathsTitle" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "SystemProgressBar" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "TaskbarProgressBar" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "AsArchives" /t REG_SZ /d "*.exe" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\CmdWin" /ve /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Comment" /v "LeftBorder" /t REG_DWORD /d "744" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\ErrList" /v "ResPlacement" /t REG_BINARY /d "2c0000000000000001000000ffffffffffffffffffffffffffffffffa3030000170200005c06000089030000" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\MainWin" /v "Placement" /t REG_BINARY /d "2c0000000000000001000000ffffffffffffffffffffffffffffffffc90a000040040000070f00003f080000" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Themes" /v "ActivePath" /t REG_SZ /d "HUDApocalypse.theme" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Themes" /v "ShellExtBMP" /t REG_SZ /d "C:\Program Files\WinRAR\Themes\HUDApocalypse.theme\RarSmall.bmp" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Themes" /v "ShellExtIcon" /t REG_SZ /d "C:\Program Files\WinRAR\Themes\HUDApocalypse.theme\Rar.ico" /f
Reg.exe add "HKCU\Software\WinRAR\Paths" /v "TempFolder" /t REG_SZ /d "C:\Users\Administrator\AppData\Local\Temp" /f
Reg.exe add "HKCU\Software\WinRAR\Paths" /v "TempRemovableOnly" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Paths" /v "StartFolder" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Name" /t REG_SZ /d "Default Profile" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Default" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ImmExec" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ExclNames" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "StoreNames" /t REG_SZ /d "*.rar *.zip *.zipx *.cab *.7z *.ace *.arj *.bz2 *.gz *.lha *.lz *.lzh *.taz *.tbz2 *.tgz *.xz *.txz *.tzst *.z *.zst" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "UseRAR" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXModule" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXIcon" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXLogo" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmtFile" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmtTextData" /t REG_BINARY /d "00" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VolumeSize" /t REG_SZ /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VolPause" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "OldVolNames" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "RecVolNumber" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Update" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Fresh" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SyncFiles" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Move" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Solid" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "AV" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Test" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Recovery" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "EraseDest" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "AddArcOnly" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ClearArc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Lock" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Method" /t REG_DWORD /d "5" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "DictSizeLZ" /t REG_DWORD /d "4194304" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Background" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "WaitForOther" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Shutdown" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Password" /t REG_BINARY /d "49" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "EncryptHeaders" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "OpenShared" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ProcessOwners" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SaveStreams" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "GenerateArcName" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VersionControl" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "GenerateMask" /t REG_SZ /d "yyyymmddhhmmss" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileTimeMode" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileDays" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileHours" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileMinutes" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileTimeBefore" /t REG_DWORD /d "2281701376" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileTimeAfter" /t REG_DWORD /d "2281701376" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcTimeOriginal" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcTimeLatest" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "mtime" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ctime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "atime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PathsAbs" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PathsNone" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PathsAbsDrive" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SeparateArc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "EmailArcTo" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackDetails" /t REG_BINARY /d "000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXLogo2" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXElevate" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmtDataWide" /t REG_BINARY /d "0000" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VolSizeMod" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Overwrite" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcRecBin" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcWipe" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "WipeIfPassword" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "RecEnabled" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "RecSize" /t REG_DWORD /d "4294967293" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "DictSizeKB" /t REG_DWORD /d "65536" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PasswordData" /t REG_BINARY /d "00" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ZipLegacyEncrypt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SaveSymLinks" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SaveHardLinks" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "BLAKE2" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileCopies" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "OrigArcData" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "QuickOpen" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PreserveAtime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SeparateArcDoubleExt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SeparateArcSubfolders" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackLongRange" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackDeltaComp" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackExeComp" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackExhaustive" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmdSwitches" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "ShellExt" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "CascadedMenu" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "MenuIcons" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "LegacyMenu" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "CustomExt" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "Type" /t REG_SZ /d "CABFolder" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.iso" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.jar" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lha" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lha" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lha" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.taz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.taz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.taz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz2" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz2" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz2" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tgz" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tgz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tgz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tlz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tlz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tlz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.txz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.txz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.txz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tzst" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tzst" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tzst" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uu" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uu" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uu" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xxe" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xxe" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xxe" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "Type" /t REG_SZ /d "CompressedFolder" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\Links" /v "Desktop" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\Links" /v "StartMenu" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\Links" /v "Programs" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "ExtrTo" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "ExtrHere" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "Extr" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "ExtrSep" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "OpenSFX" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "AddTo" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "AddArc" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "EmailArc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "EmailOpt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "Test" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "Convert" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Type" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "DosCharSet" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ReuseWindow" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Wrap" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ViewerUnpackAll" /t REG_SZ /d "*.exe *.msi *.htm *.html *.part*.rar" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ExternalViewer" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Autodetect" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ViewerIgnoreModifications" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\VirusScan" /v "Prompt" /t REG_DWORD /d "1" /f
Exit

:IsAdmin
Reg.exe query "HKU\S-1-5-19\Environment"
If Not %ERRORLEVEL% EQU 0 (
 Cls & Echo You must have administrator rights to continue ... 
 Pause & Exit
)
Cls
goto:eof
