@Echo Off
Title Reg Converter v1.2 & Color 1A
cd %systemroot%\system32
call :IsAdmin

Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DictHistorySize" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DictMask" /t REG_SZ /d "0000001100000000000000000000000000000000000000000000000000000000000000000" /f
Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DictLimit" /t REG_DWORD /d "8" /f
Reg.exe add "HKCU\Software\WinRAR\Compression" /v "DefFolder" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Vol5MB" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Vol100MB" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "CD700" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Vol2GB" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "FAT32" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "DVD+R" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "DVD-R" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "DVD DL" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Blu-ray" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Blu-ray DL" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "Autodetect" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "History" /t REG_DWORD /d "3" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel0" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize0" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel1" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize1" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel2" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize2" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserLabel3" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Compression\Volumes" /v "UserSize3" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "DefFolder" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "AppendName" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "RemoveRedundantFolder" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "UseExclNames" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "ExclNames" /t REG_SZ /d "*.exe *.com *.pif *.scr *.bat *.cmd *.lnk" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "MOTWMode" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Extraction" /v "MOTWZoneOnly" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Detailed" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ArchivesFirst" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ColorAttr" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "AllVolumes" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ShowSeconds" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ExactSizes" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ShowGrid" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "FullRow" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Checkboxes" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "SingleClick" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Underline" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "ArcSort" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "FileSort" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "Font" /t REG_BINARY /d "efffffff0000000000000000000000009001000000000000030201225300650067006f006500200055004900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" /f
Reg.exe add "HKCU\Software\WinRAR\FileList" /v "FontColorDark" /t REG_DWORD /d "16777215" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "name" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "size" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "psize" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "type" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "mtime" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "ctime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "atime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "attr" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "crc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnStates" /v "path" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "name" /t REG_DWORD /d "343" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "size" /t REG_DWORD /d "116" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "psize" /t REG_DWORD /d "116" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "type" /t REG_DWORD /d "88" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "mtime" /t REG_DWORD /d "154" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\ArcColumnWidths" /v "crc" /t REG_DWORD /d "70" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "name" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "size" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "psize" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "type" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "mtime" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "ctime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "atime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "attr" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "crc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnStates" /v "path" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "name" /t REG_DWORD /d "367" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "size" /t REG_DWORD /d "103" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "type" /t REG_DWORD /d "216" /f
Reg.exe add "HKCU\Software\WinRAR\FileList\FileColumnWidths" /v "mtime" /t REG_DWORD /d "155" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "VerInfo" /t REG_BINARY /d "00160700e110da3d3bdadc01" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "History" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "DlgHistory" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "WizardMode" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "OnTop" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "ShowComment" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "WrapComment" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "ReuseWindow" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Sound" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Priority" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Threads" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LargePages" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "Log" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LimitLog" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "LogSize" /t REG_DWORD /d "1000" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "RestoreFolder" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General" /v "WipeTemp" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar" /v "Size" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar" /v "ButtonsText" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar" /v "Lock" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.add" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.add.pos" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.add.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.add" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.add.pos" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.add.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.exto" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.exto.pos" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.exto.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.exto" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.exto.pos" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.exto.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.test" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.test.pos" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.test.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.test" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.test.pos" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.test.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.view" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.view.pos" /t REG_DWORD /d "3" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.view.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.view" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.view.pos" /t REG_DWORD /d "3" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.view.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.del" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.del.pos" /t REG_DWORD /d "4" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.del.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.del" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.del.pos" /t REG_DWORD /d "4" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.del.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.find" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.find.pos" /t REG_DWORD /d "5" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.find.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.find" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.find.pos" /t REG_DWORD /d "5" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.find.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.prn" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.prn.pos" /t REG_DWORD /d "6" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.prn.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.prn" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.prn.pos" /t REG_DWORD /d "6" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.prn.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.wiz" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.wiz.pos" /t REG_DWORD /d "7" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.wiz.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.wiz" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.wiz.pos" /t REG_DWORD /d "7" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.wiz.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.cvt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.cvt.pos" /t REG_DWORD /d "8" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.cvt.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.cvt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.cvt.pos" /t REG_DWORD /d "8" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.cvt.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.info" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.info.pos" /t REG_DWORD /d "9" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.info.sep" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.info" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.info.pos" /t REG_DWORD /d "9" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.info.sep" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.exit" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.exit.pos" /t REG_DWORD /d "11" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.exit.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.exit" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.exit.pos" /t REG_DWORD /d "11" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.exit.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.rep" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.rep.pos" /t REG_DWORD /d "12" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.rep.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.rep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.rep.pos" /t REG_DWORD /d "12" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.rep.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.extr" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.extr.pos" /t REG_DWORD /d "13" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.extr.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.extr" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.extr.pos" /t REG_DWORD /d "13" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.extr.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.vir" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.vir.pos" /t REG_DWORD /d "14" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.vir.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.vir" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.vir.pos" /t REG_DWORD /d "14" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.vir.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.cmt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.cmt.pos" /t REG_DWORD /d "15" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.cmt.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.cmt" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.cmt.pos" /t REG_DWORD /d "15" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.cmt.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.prot" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.prot.pos" /t REG_DWORD /d "16" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.prot.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.prot" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.prot.pos" /t REG_DWORD /d "16" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.prot.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.lock" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.lock.pos" /t REG_DWORD /d "17" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.lock.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.lock" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.lock.pos" /t REG_DWORD /d "17" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.lock.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.sfx" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.sfx.pos" /t REG_DWORD /d "18" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.sfx.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.sfx" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.sfx.pos" /t REG_DWORD /d "18" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.sfx.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.rpt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.rpt.pos" /t REG_DWORD /d "19" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.rpt.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.rpt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.rpt.pos" /t REG_DWORD /d "19" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.rpt.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.bnc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.bnc.pos" /t REG_DWORD /d "20" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "f.bnc.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.bnc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.bnc.pos" /t REG_DWORD /d "20" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Buttons" /v "a.bnc.sep" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Layout" /v "Band76_0" /t REG_BINARY /d "4c000000610100000402000000000000000000000000000000000000000000000000000000000000000000000000000000000000550000003402000000000000000000000000000001000000" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Layout" /v "Band76_1" /t REG_BINARY /d "4c0000006101000005000000000000000000000000000000000000000000000000000000000000000000000000000000000000001d0000002600000000000000000000000000000002000000" /f
Reg.exe add "HKCU\Software\WinRAR\General\Toolbar\Layout" /v "Band76_2" /t REG_BINARY /d "4c0000006101000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000001d0000006400000000000000000000000000000003000000" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "ColorMode" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "FullPathsTitle" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "SystemProgressBar" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "TaskbarProgressBar" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "AsArchives" /t REG_SZ /d "*.exe" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "ShowPassword" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Interface" /v "PswAllArchives" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\CmdWin" /ve /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Comment" /v "LeftBorder" /t REG_DWORD /d "696" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\ErrList" /v "ResPlacement" /t REG_BINARY /d "2c0000000000000001000000fffffffffffffffffffffffffffffffff60a000096010000210e0000f5030000" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\MainWin" /v "Placement" /t REG_BINARY /d "2c0000000000000001000000ffffffffffffffffffffffffffffffffb80a0000f5030000ff0e0000fb070000" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Themes" /v "ActivePath" /t REG_SZ /d "HUDApocalypse.theme" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Themes" /v "ShellExtBMP" /t REG_SZ /d "C:\Program Files\WinRAR\Themes\HUDApocalypse.theme\RarSmall.bmp" /f
Reg.exe add "HKCU\Software\WinRAR\Interface\Themes" /v "ShellExtIcon" /t REG_SZ /d "C:\Program Files\WinRAR\Themes\HUDApocalypse.theme\Rar.ico" /f
Reg.exe add "HKCU\Software\WinRAR\Paths" /v "TempFolder" /t REG_SZ /d "C:\Users\Administrator\AppData\Local\Temp" /f
Reg.exe add "HKCU\Software\WinRAR\Paths" /v "TempRemovableOnly" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Paths" /v "StartFolder" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Name" /t REG_SZ /d "Default Profile" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Default" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ImmExec" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ExclNames" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "StoreNames" /t REG_SZ /d "*.rar *.zip *.zipx *.cab *.7z *.ace *.arj *.bz2 *.gz *.lha *.lz *.lzh *.taz *.tbz2 *.tgz *.xz *.txz *.tzst *.z *.zst" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "UseRAR" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXModule" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXIcon" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXLogo" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmtFile" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmtTextData" /t REG_BINARY /d "00" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VolumeSize" /t REG_SZ /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VolPause" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "OldVolNames" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "RecVolNumber" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Update" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Fresh" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SyncFiles" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Move" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Solid" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "AV" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Test" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Recovery" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "EraseDest" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "AddArcOnly" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ClearArc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Lock" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Method" /t REG_DWORD /d "5" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "DictSizeLZ" /t REG_DWORD /d "4194304" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Background" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "WaitForOther" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Shutdown" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Password" /t REG_BINARY /d "49" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "EncryptHeaders" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "OpenShared" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ProcessOwners" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SaveStreams" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "GenerateArcName" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VersionControl" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "GenerateMask" /t REG_SZ /d "yyyymmddhhmmss" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileTimeMode" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileDays" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileHours" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileMinutes" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileTimeBefore" /t REG_DWORD /d "2281701376" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileTimeAfter" /t REG_DWORD /d "2281701376" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcTimeOriginal" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcTimeLatest" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "mtime" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ctime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "atime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PathsAbs" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PathsNone" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PathsAbsDrive" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SeparateArc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "EmailArcTo" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackDetails" /t REG_BINARY /d "000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXLogo2" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SFXElevate" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmtDataWide" /t REG_BINARY /d "0000" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "VolSizeMod" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "Overwrite" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcRecBin" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ArcWipe" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "WipeIfPassword" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "RecEnabled" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "RecSize" /t REG_DWORD /d "4294967293" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "DictSizeKB" /t REG_DWORD /d "65536" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PasswordData" /t REG_BINARY /d "00" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "ZipLegacyEncrypt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SaveSymLinks" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SaveHardLinks" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "BLAKE2" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "FileCopies" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "OrigArcData" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "QuickOpen" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PreserveAtime" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SeparateArcDoubleExt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "SeparateArcSubfolders" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackLongRange" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackDeltaComp" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackExeComp" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "PackExhaustive" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Profiles\0" /v "CmdSwitches" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "ShellExt" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "CascadedMenu" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "MenuIcons" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "LegacyMenu" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup" /v "CustomExt" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.001" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.7z" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.arj" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.bz2" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "Type" /t REG_SZ /d "CABFolder" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.cab" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.gz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.iso" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.jar" /v "Set" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lha" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lha" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lha" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.lzh" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.rar" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tar" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.taz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.taz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.taz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz2" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz2" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tbz2" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tgz" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tgz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tgz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tlz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tlz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tlz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.txz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.txz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.txz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tzst" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tzst" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.tzst" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uu" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uu" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uu" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.uue" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xxe" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xxe" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xxe" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.xz" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.z" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "Exist" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "Type" /t REG_SZ /d "CompressedFolder" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zip" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zipx" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "Set" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "Exist" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "Type" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\.zst" /v "ShellNew" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\Links" /v "Desktop" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\Links" /v "StartMenu" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\Links" /v "Programs" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "ExtrTo" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "ExtrHere" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "Extr" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "ExtrSep" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "OpenSFX" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "AddTo" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "AddArc" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "EmailArc" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "EmailOpt" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "Test" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Setup\MenuItems" /v "Convert" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Type" /t REG_DWORD /d "2" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "DosCharSet" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ReuseWindow" /t REG_DWORD /d "0" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Wrap" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ViewerUnpackAll" /t REG_SZ /d "*.exe *.msi *.htm *.html *.part*.rar" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ExternalViewer" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Autodetect" /t REG_DWORD /d "1" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "ViewerIgnoreModifications" /t REG_SZ /d "" /f
Reg.exe add "HKCU\Software\WinRAR\Viewer" /v "Placement" /t REG_BINARY /d "2c0000000000000001000000ffffffffffffffffffffffffffffffff7405000085010000b60800003c050000" /f
Reg.exe add "HKCU\Software\WinRAR\VirusScan" /v "Prompt" /t REG_DWORD /d "1" /f
Exit

:IsAdmin
Reg.exe query "HKU\S-1-5-19\Environment"
If Not %ERRORLEVEL% EQU 0 (
 Cls & Echo You must have administrator rights to continue ... 
 Pause & Exit
)
Cls
goto:eof
